### ISSUE TITLE
Intro: Anil Sahintürk [ansa]

### ISSUE THREAD

**Issue by AnilSahintuerk** [FUB-HCC/hcds-winter-2020#11]
Hello everyone my name is Anil. 

I am in my 7th semester in the bachelor of computer science. I enjoy programming with python and recently started some automation / webscraping projects for fun. In data science I do not have a real knowledge base I just did some tutorials on youtube. But I hope this course pushes me to learn more about it with the coding assignments.

It may sound nerdy but I like to learn more about the process of working with data. And that is also the reason why I took courses like Machine Learning, Stochastik and Statistics. My goal for this semester is to get my unfished courses done so I can fully concentrate on my bachelor thesis for next semester.

I hope we all have a great time together!

Anil

**Comment by jonas-weber** [comment]
Hey Anil! What Stochastik and Statistics courses did you take this year? I wanted to take some for the same reasons as you, but the Stochastik courses in the Math Department didn't look fun at all, which is why I enrolled in _Schließende Statistik_ in the WiWiss department. Which one did you take? And do you already know what topic your bachelor thesis is going to be about?

**Comment by yuxin16** [comment]
Hi, it is so nice that you have a solid background in math&algorithm. Did you take the Machine Learning by Prof. Tim Landgraf? I was still considering taking this course and may I ask your experience of it?

**Comment by yuxin16** [comment]
> 
> 
> Hey Anil! What Stochastik and Statistics courses did you take this year? I wanted to take some for the same reasons as you, but the Stochastik courses in the Math Department didn't look fun at all, which is why I enrolled in _Schließende Statistik_ in the WiWiss department. Which one did you take? And do you already know what topic your bachelor thesis is going to be about?

Hello, here is someone from Wiwiss and regreted having taken it from Wiwiss. I wished I could have taken it from Math/Info. I think the course in Wiwiss is more conceptual but without solid mathematic theoretical background  (have to say, easier than that from maths) . I don't think it is a good preparation for further statistical courses such as stochastics/markov/monte carlo.

**Comment by AnilSahintuerk** [comment]
Stochastik is from the math deparment and Statistics form the bioinformatik. Sadly I have no Bachelor thesis yet but I am sure I will find one soon.

Thanks for the comment and sorry for the late answer @jonas-weber

**Comment by AnilSahintuerk** [comment]
@yuxin16 yeah it's the course from Prof. Landgraf until now it is really fun I like the way he handles the lectures (uploading videos on youtube with slides). If you are still interested how this course was at the end of the semester just ask me again and I can give you a better report :D
