### ISSUE TITLE
Assignment A2

### ISSUE THREAD

**Issue by aschle** [FUB-HCC/hcds-winter-2020#19]
https://github.com/FUB-HCC/hcds-winter-2020/wiki/02_exercise#a2---reproducibility-workflow

❓ **Question**: "I have a question regarding the latest assignment. I wonder what those 5 queries are we shall do because I do count a total of 6 if you do 2x mobile, 2x desktop and 2x all (2x=legacy, pageviews):.

**Answer**: "It should be: legacy_desktop, legacy_mobile, pageviews_desktop, pageviews_mobile_app, pageviews_mobile_web

Pageview API has mobile-web and mobile-appas params. Does this help you?

**Comment by mvrcx** [comment]
Hey Alexa, I wasn't sure about this point: "Name your repository prefixed with A2-hcds-hcc". Is committing the assignment in the correct folder enough? If not how do I do it?

**Comment by aschle** [comment]
Hey @mvrcx,  this means creating a separate GitHub repository. As this task is about "reproducibility research" your assignment should live in a separate repo. So someone else could take your repository (e.g. fork it) and redo your analysis.
