### ISSUE TITLE
[R3 - Reflection] Reflect about what?

### ISSUE THREAD

**Issue by marisanest** [FUB-HCC/hcds-winter-2020#21]
Hey,

I have one short question about Reflection R3:

The [blog.md](https://github.com/FUB-HCC/hcds-winter-2020/blob/main/assignments/A3_Bias/alsc/blog.md) template for the R3 states:
> Video: The Trouble with Bias - NIPS 2017 Keynote - Kate Crawford #NIPS2017.

Whereas the [Wiki](https://github.com/FUB-HCC/hcds-winter-2020/wiki/03_exercise) says:
> Read the article 📄 “Algorithmic Profiling of Job Seekers in Austria: How Austerity Politics Are Made Effective”[1] about the AMS system in Austria.

Which source is the correct one?

Thanks!

**Comment by aschle** [comment]
This one --> **Read the article 📄 “Algorithmic Profiling of Job Seekers in Austria: How Austerity Politics Are Made Effective”[1] about the AMS system in Austria.**

I will correct the blog template! Thanks!
