### ISSUE TITLE
Access to the GitHub repo

### ISSUE THREAD

**Issue by aschle** [FUB-HCC/hcds-winter-2020#3]
Please add you GitHub username to this ticket, so I can add you as a contributor. You can use your private account or just create a new one for this course, as you like.

**Comment by satorus** [comment]
satorus

**Comment by malina-scheuer** [comment]
malina-scheuer

**Comment by Francosinus** [comment]
Francosinus

**Comment by kuzniarz** [comment]
kuzniarz

**Comment by lukaskaibel** [comment]
lukaskaibel

**Comment by chrisk280** [comment]
chrisk280

**Comment by lpolari** [comment]
lpolari

**Comment by AnilSahintuerk** [comment]
AnilSahintuerk

**Comment by marisanest** [comment]
marisanest

**Comment by Arne117** [comment]
Arne117

**Comment by chrisk280** [comment]
@aschle Hallo Alexa, ich habe Probleme meine Ergebnisse zu pushen. Könntest du noch einmal überprüfen, ob ich die nötigen Berechtigungen habe?
Wenn ja, muss ich noch genau bei mir nachschauen, wo das schief läuft.

**Comment by jonas-weber** [comment]
jonas-weber

**Comment by Alioio** [comment]
My GitHub username: Alioio

**Comment by yuxin16** [comment]
My GitHub username: yuxin16

**Comment by Nigrog** [comment]
Nigrog

**Comment by mvrcx** [comment]
mvrcx

**Comment by aschle** [comment]
OK, I think everybody is now in GitHub!
