### ISSUE TITLE
Intro: Christopher Kilian [chki]  

### ISSUE THREAD

**Issue by chrisk280** [FUB-HCC/hcds-winter-2020#9]
Hello everyone,

my name is Christopher and I am in the third semester in the Master's degree of Computer Science. I decided to attend HCDS for two main reasons. On the one hand, I attended HCI last semester and I really liked it. That's why I want to get deeper into related topics (like HCDS). On the other hand, I worked with data and jupyter notebooks in the past but never had a lecture on (or related to) data science at university. So I hope to gain some new insights in this lecture.

While I am quite familiar with Jupyter Notebooks/Python/Git, I probably lack some knowledge regarding statistics and certain algorithms used in data science (I have a little experience).

I'm looking forward to meet you in the tutorials!

Christopher

**Comment by mvrcx** [comment]
seems like this course is just perfect for you ;)

**Comment by AnilSahintuerk** [comment]
I think you have a good basis to master the upcoming challanges easily :)

**Comment by Arne117** [comment]
So it seems like we have two courses this semester together ✌

**Comment by aschle** [comment]
OK now I understand, why I did not look into your `A1`, this ticket is closed, so I thought you left the course 🤷.

**Comment by chrisk280** [comment]
I wanted to clean up the list of issues (and the assignment was done already). Shall I reopen it?
